### ISSUE TITLE
Add support for OSM relations

### ISSUE THREAD

**Issue by maning** [mapbox/minjur#8] opened 2015-12-07 04:30 UTC
Geojson doesn't have direct support for OSM relations.  Some prior art from Overpass API: http://wiki.openstreetmap.org/wiki/Overpass_turbo/GeoJSON

**Comment by rclark** [comment] 2016-02-04 18:05
@joto What are your thoughts on implementing relation support in minjur? It sounded like you felt like it would represent a significant overhaul to how poly / multipoly handling works here?

I could really use this feature, and wouldn't mind trying to implement it if you don't mind some hand-holding or have decent libosmium examples already laying around.

**Comment by joto** [comment] 2016-02-04 22:18
Yes, this is a totally different beast, because, to make updates possible, some kind of database would be needed.

**Comment by rclark** [comment] 2016-02-04 23:17
Ok -- I'm only looking for one-off, wholesale conversion of a planet data file to geojson. Am I looking in the wrong place?

**Comment by joto** [comment] 2016-02-05 08:20
Okay, one-off conversion without updates is easier. There is some problem with the multipolygon generation, as it is much slower on the whole planet file than I would expect from testing with smaller files. I am trying to track down where the problem is. Until this is getting a bit faster than it is now, running the whole planet is probably too slow. Last time I broke the process off after 10 hours or so.

**Comment by rclark** [comment] 2016-02-05 16:45
At this point I would be happy to _just be able to do this_, even if it takes 24 hours. The other approach I'm trying right now is to do this via node-osmium, where I'm running into https://github.com/osmcode/node-osmium/issues/69, even on an EC2 with 60GB of RAM.

**Comment by joto** [comment] 2016-02-05 20:31
@rclark  I have just added a `minjur-mp` program that will assemble multipolygons and doesn't do updates, apart from that it is basically the same as the original minjur. Try it out and see how well it works for you. This will take some time and will need a lot of memory. I suggest starting out with small test files and then work your way up to the planet. I'd be interested in the numbers how long it takes and how much memory it needs on your setup. Meanwhile I'll keep looking into speeding things up. It should be possible to make this faster.

**Comment by rclark** [comment] 2016-02-08 15:04
I grabbed this new executable on Friday and set it to work on the planet. 65 hours later, it is still running, but I just realized that I forgot to set the `-n dense` flag. I also didn't set the `-p` flag.... oops. 

Output so far has been:

```
Using the 'sparse_mmap_array' location store. Use -l or -n to change this.
Reading from 'planet.osm.pbf'...
Pass 1...
Pass 1 done
Pass 2...
```

Appears to have one CPU pegged at 100%, and be using 86% of the available RAM out of 60GB.

**Comment by rclark** [comment] 2016-02-11 00:42
In case this is of any help @joto, here's a `perf report` collected from the long-running process: https://gist.github.com/rclark/c03fb67115fc59503f82 (thanks to @springmeyer's [profiling guide](https://github.com/springmeyer/profiling-guide#perf-record))

**Comment by joto** [comment] 2016-02-15 15:06
@rclark I just pushed a new version of libosmium where the multipolygon code is an order of magnitude faster than in the old version! There is still more I want to optimize, but I think this should make minjur-mp usable now. Recompile with the current libosmium master and try it out.

**Comment by rclark** [comment] 2016-02-15 21:24
```
time minjur-mp -n dense planet.osm.pbf | split --lines 1000000 --suffix-length 4 - output/geojson.                                                       
Using the 'dense_mmap_array' location store. Use -l or -n to change this.
Reading from 'planet.osm.pbf'...
Pass 1...
Pass 1 done
Pass 2...
Pass 2 done
Number of geometry errors (not written to output): 23544
Done.

real    156m40.933s
user    177m2.264s
sys     13m47.742s
```

> an order of magnitude faster

Should've read "several orders of magnitude". The next step is to investigate the outputs more -- I'm a little concerned that it generated 652 files of supposedly 1,000,000 features a piece. I don't believe there ought to be 652 million features so I'll be going on a duplicate-hunt.

**Comment by joto** [comment] 2016-02-16 09:06
The number of 652 million features sounds about right. There are 107 million nodes with at least one tag, 331 million ways of which 215 million are closed, and 2 million multipolygon relations. Closed ways will show up twice, once as LineString, once as Polygon. minjur doesn't know about tags, so it can't differentiate between, say, a closed way that's a building and one that's a highway roundabout. 107+331+215+2=655. So give or take some closed ways in multipolygon relations and some rounding errors, the result sounds right.

**Comment by rclark** [comment] 2016-02-16 15:28
Sounds great, and the performance is excellent. Do you intend to keep `minjur` and `minjur-mp` as two separate tools? Or could they be merged to one with multipolygon generation being perhaps an optional flag?

**Comment by joto** [comment] 2016-02-16 15:35
Lets keep it as two tools for the time being and see where it goes. There is a big difference between the two, because `minjur` can work with updates and `minjur-mp` doesn't. Sooner or later we'll have to revisit this anway.

**Comment by springmeyer** [comment] 2016-02-17 00:50
I've been enjoying following along on the progress here. Awesome work @joto and @rclark. I understand that when updates are not needed `minjur-mp` is the tool for the job and is now quite a bit faster with latest libosmium linked in. In terms of @maning's original question about supporting OSM relations: where do we stand on that?

**Comment by joto** [comment] 2016-02-17 08:33
@springmeyer When @maning talked about "support for OSM relations" I assumed he was talking about _multipolygon relations_ (especially because the link he points to only mentions multipolygons).
Generally relations don't necessarily have a geometry, so it is unclear how they should be represented in a _geojson_ file.

By far the most common type of relation is the multipolygon relation and it is also the most generally useful one. Of course there are other types, such as `route` relations, which have a geometry. But each of those cases has to be handled specially. Libosmium has basic support for all kinds of relations in that the `Collector` can find all the members of a relation together. But in a second step these pieces have to be assembled into something, an area, a route, or whatever. And that `Assembler` code only exists for multipolygons. I always expected there to be more assemblers in the future, but haven't had the need yet to write them. I know that others have built on libosmium and done things like that, though.

@maning Please chime in if I misunderstood you and you are also interested in other kinds of relations.

**Comment by maning** [comment] 2016-02-19 14:58
@joto, what I have in mind was multipolygon relations. My original query was related to using osm-qa-tiles for processing untagged ways in osmlint.

@rub21

**Comment by joto** [comment] 2016-02-20 08:20
@maning Okay, that's a really tricky one and not solved by `minjur-mp`. If I understand correctly, it seems very easy: You want to find all ways without any tags that are not members of any relation. But neither the QA tiles generated with `minjur` nor `minjur-mp` contain this kind of information, because the QA tiles concentrate on the "geometry" aspect of the OSM data, ignoring "relations" between objects. On the other hand it would be very easy to generate this kind of information directly from a planet file using libosmium. If you need something like this, open a ticket against `data` and ping me.

**Comment by maning** [comment] 2016-02-20 14:07
@joto, nothing immediate for now, we would like to maintain the use of osm-qa-tiles and osmlint.

**Comment by springmeyer** [comment] 2016-02-20 16:11
Thanks for the followups everyone. I will now close this issue as it sounds like any further ideas can be handled in new issues.

**Closed as completed by springmeyer** 2016-02-20 16:11 UTC
